global:
  external_labels:
    monitor: "crm-monitor"

scrape_configs:
  # - job_name: "traefik"
  #   scrape_interval: 15s
  #   scrape_timeout: 10s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #     - targets:
  #         - traefik:8082

  # - job_name: "api-node"
  #   scrape_interval: 15s
  #   scrape_timeout: 10s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #     - targets:
  #         - api-node:3000
