{
 "title": "Traefik",
 "time": { "from": "now/d", "to": "now/d" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "job", "label": "Job:", "query": { "query": "label_values(job)" } },
   {
    "name": "service",
    "label": "Service",
    "query": {
     "query": "label_values(traefik_service_requests_total{job=~\"[[job]]\"},service)"
    }
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": {
     "query": "label_values(traefik_service_requests_total, protocol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Traefik Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum{job=~\"$job\"}) / sum(traefik_entrypoint_requests_total{job=~\"$job\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server-side Error",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total{code=~\"5\\\\d\\\\d\", job=~\"$job\", service=~\"$service\", protocol=~\"$protocol\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client-side Error",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total{code=~\"4\\\\d\\\\d\", job=~\"$job\", service=~\"$service\", protocol=~\"$protocol\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "None-error Response",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(traefik_service_requests_total{code=~\"(2|3)\\\\d\\\\d\", job=~\"$job\", service=~\"$service\", protocol=~\"$protocol\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Return Codes",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(   label_replace(     traefik_service_requests_total{       protocol=~\"$protocol\",       job=~\"$job\",       service=~\"$service\"     },    \"response_code\",  \"$1,xx\", \"code\", \"(\\\\d).+\") )  by (response_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service open connection",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 8, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(  traefik_service_open_connections{   job=~\"$job\", service=~\"$service\"} ) by (method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average response time by service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum( traefik_service_request_duration_seconds_sum{job=~\"$job\",service=~\"$service\",protocol=~\"$protocol\"} ) by (service) / sum( traefik_service_request_duration_seconds_count{job=~\"$job\",service=~\"$service\",protocol=~\"$protocol\"} ) by (service)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}